### ISSUE TITLE
Writing Checklist

### ISSUE THREAD

**Issue by katyhuff** [arfc/ddca_numerical_exp#27]
A checklist exists for writing properly... 
http://arfc.github.io/manual/guides/writing/checklist/

This issue can be closed when the following items have been checked in the DDCA July 2019 report. 

- [x] Run a spell checker.
- [x] The Oxford comma appears in  ("lions, tigers, and bears.")
- [x] Do not use the word "where" unless referring to a location (try "such that" or "in which").
- [x] Articles such as "a" "the" "some" "any" and "each" appear where necessary.
- [x] All subjects match the plurality of their verbs ( no: "Apples is tasty" yes: "Apples are tasty")
- [x] Avoid run-on sentences.
- [x] clunky nouns -> spunky verbs (progression, expression --> progress, express)
- [x] reduce vague words (important, methodologic)
- [x] reduce acronyms / jargon
- [x] get rid of unnecessary prepositional phrases -- author clearing throat (It can be shown that)
- [x] get rid of extraneous adverbs (very, really, quite, basically, generally)
- [x] get rid of there are / there is
- [x] turn negatives to positives (she was not often right -> she was usually wrong)
- [x] get rid of extraneous prepositions (the meeting happened on monday -> the meeting happened monday) (they agreed that it was true -> they agreed it was true)
- [x] get rid of passive voice (is/was/are/were/be/been/am + past tense verb), replace with active voice
- [x] use strong verbs (use sparingly: is, are, was, were, be, been, am)
- [x] avoid turning verbs into nouns ("obtain estimates of" -> "estimates"; "provides a description of" -> "describes") 
- [x] don't bury the verb (keep the predicate close to the subject at the beginning of the sentence)
- [x] data is plural (the data are critical)
- [x] compare to (point out similarities between different things) vs.  compared with (point out differences between similar things)
- [x] punctuation helps you to vary your sentence structure
- [x] Power to separate in increasing power: comma, colon, dash, parentheses, semicolon, period
- [x] In increasing order of formality: dash, parentheses, all of the others. Don't overdo it with the dash and parentheses
- [x] semicolon: connects two independent clauses. OR used to separate when the items in the list contain internal punctuation.
- [x] use a colon to introduce a list, quote, explanation, conclusion, or amplification
- [x] if there's a list in a sentence, it shouldn't come before the colon
- [x] use a dash to insert something in the middle of the sentence. Don't overuse it.

**Comment by katyhuff** [comment]
Closed with #31.
